const { chromium } = require('playwright');
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const output = path.resolve(__dirname, '../test-results');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:4173';
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.PW_CHANNEL ? {channel:process.env.PW_CHANNEL} : {})});
  const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror', error=>errors.push(error.message));
  page.on('console', msg=>{if(msg.type()==='error')errors.push(msg.text());});
  await page.goto(base, {waitUntil:'networkidle'});
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.project-card > picture > img').count(),4);
  assert.equal(await page.locator('.project-card .preview-copy, .project-card .preview-nav, .project-card .preview-footer').count(),0);
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  assert.equal(await page.locator('#project-title').textContent(),"Andy's");
  await page.locator('#next').click();
  assert.equal(await page.locator('#project-title').textContent(),'ЭМСОТЕХ');
  await page.locator('#next').click();
  assert.equal(await page.locator('#project-title').textContent(),'АРТКОМ');
  await page.locator('#next').click();
  assert.equal(await page.locator('#project-title').textContent(),'Альфа-Лаб');
  await page.locator('#next').click();
  assert.equal(await page.locator('#project-title').textContent(),"Andy's");
  await page.locator('.project-slider').focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#project-title').textContent(),'Альфа-Лаб');
  await page.locator('#project-open').click();
  assert.equal(await page.locator('#detail-link').getAttribute('href'),'https://cleanroomshop.ru/');
  await page.keyboard.press('Escape');
  await page.locator('[data-slide="0"]').click();
  await page.locator('#project-open').click();
  assert(await page.locator('#project-dialog').evaluate(n=>n.open));
  assert.equal(await page.locator('#detail-title').textContent(),"Andy's");
  assert.equal(await page.locator('#detail-link').getAttribute('href'),'https://andys.rest/');
  await page.keyboard.press('Escape');
  assert(!await page.locator('#project-dialog').evaluate(n=>n.open));
  assert.equal(await page.evaluate(()=>document.activeElement.id),'project-open');
  await page.locator('[data-contact].button-primary').click();
  assert(await page.locator('#contact-dialog').evaluate(n=>n.open));
  assert.equal(await page.locator('#contact-links a').first().getAttribute('href'),'https://t.me/Garmanika');
  assert((await page.locator('#contact-links a').nth(1).getAttribute('href')).startsWith('mailto:aleks.orlov97%40gmail.com'));
  await page.keyboard.press('Escape');
  const viewports=[];
  const imageChecks=[];
  for (const width of [1440,1024,769,768,540,390,320]) {
    await page.setViewportSize({width,height:900});
    await page.evaluate(()=>Promise.all([...document.querySelectorAll(".project-card img")].map(n=>n.decode())));
    const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,broken:[...document.images].filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src)}));
    assert(metrics.scrollWidth<=width,`Horizontal overflow at ${width}: ${metrics.scrollWidth}`);
    assert.deepEqual(metrics.broken,[]);
    viewports.push(metrics);
    for (let i=0;i<4;i++) {
      await page.locator(`[data-slide="${i}"]`).click();
      const card = page.locator('.project-card[aria-hidden="false"] > picture > img');
      await card.evaluate(n=>n.decode());
      assert.equal(await card.evaluate(n=>n.currentSrc.includes("-mobile.jpg")),width<=768,"Wrong picture source");
      const image = await card.evaluate(n=>({width:n.clientWidth,height:n.clientHeight,naturalWidth:n.naturalWidth,naturalHeight:n.naturalHeight,fit:getComputedStyle(n).objectFit}));
      assert(image.naturalWidth>0);
      assert(Math.abs(image.height-image.width*image.naturalHeight/image.naturalWidth)<2, `Cropped card ${i} at ${width}px`);
      await page.locator('#project-open').click();
      await page.locator('#detail-image').evaluate(n=>n.decode());
      assert.equal(await page.locator('#detail-image').evaluate(n=>getComputedStyle(n).objectFit),'contain', 'Detail image must not crop');
      await page.keyboard.press('Escape');
      imageChecks.push({width,project:i,result:'PASS'});
    }
  }
  await page.setViewportSize({width:1440,height:600});
  await page.locator('#project-open').click();
  assert.equal(await page.locator('#detail-image').evaluate(n=>getComputedStyle(n).objectFit),'contain');
  await page.screenshot({path:path.join(output,'short-dialog.png')});
  await page.locator('#detail-link').scrollIntoViewIfNeeded();
  assert(await page.locator('#detail-link').isVisible());
  await page.keyboard.press('Escape');
  await page.locator('[data-slide="0"]').click();
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>document.activeElement.blur());
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  // Exercise the exact touch handler without sending a request or navigating away.
  await page.locator('.slider-viewport').evaluate(n=>{
    const touch=(x,y)=>new Touch({identifier:1,target:n,clientX:x,clientY:y});
    n.dispatchEvent(new TouchEvent('touchstart',{touches:[touch(300,100)]}));
    n.dispatchEvent(new TouchEvent('touchend',{changedTouches:[touch(100,105)]}));
  });
  assert.equal(await page.locator('#project-title').textContent(),'ЭМСОТЕХ');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.slider-track').evaluate(n=>getComputedStyle(n).transitionDuration),'0s');
  const response=await page.request.get(base+'/%2e%2e%5cREADME.md');
  assert([403,404].includes(response.status()));
  assert.equal((await page.request.post(base+'/')).status(),405);
  assert.deepEqual(errors,[],'Browser errors');
  const report={result:'PASS',viewports,checks:['image-only project cards','carousel next/previous/wrap','keyboard','pagination','published project link','project dialog','Escape/focus restoration','owner contact destinations','touch swipe','reduced motion','all images loaded','no horizontal overflow','no browser errors','path traversal rejected','POST rejected']};
  fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify(report,null,2));
  fs.writeFileSync(path.join(output,'image-checks.json'),JSON.stringify(imageChecks,null,2));
  console.log(JSON.stringify(report,null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});

